2016-10-08 10:59:58.535 [error] <0.194.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.199.0> exit with reason normal in context child_terminated
2016-10-08 11:25:04.134 [error] <0.194.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.199.0> exit with reason normal in context child_terminated
2016-10-08 11:26:12.011 [error] <0.194.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.199.0> exit with reason normal in context child_terminated
2016-10-08 11:30:07.357 [error] <0.194.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.199.0> exit with reason normal in context child_terminated
2016-10-09 22:18:40.138 [error] <0.194.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.199.0> exit with reason normal in context child_terminated
2016-10-09 23:17:19.515 [error] <0.194.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.199.0> exit with reason normal in context child_terminated
2016-10-09 23:35:23.131 [error] <0.194.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.199.0> exit with reason normal in context child_terminated
